In [5]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
%matplotlib inline
from sklearn.linear_model import LinearRegression
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.decomposition import PCA
import random

In [17]:
df = pd.read_csv(r"C:\Users\Anuj Bohra\Desktop\final_vcet.csv")

In [14]:
df

,Unnamed: 0,Group,Area,exploration,communication,feedback,extracurriculars,help_others,confidence,adv_courses,Colab,Exp,Resouce,hours,class
0,0,No,Data Analysis,No,Enjoy Communicating,Verbal,7,1,2,No,Independent,1,Peer Discussion,2,Beginner
1,1,No,Computer Vision,Yes,Enjoy Communicating,Verbal,1,1,2,No,Neutral,2,TextBook,1,Beginner
2,2,No,NLP,No,Enjoy Communicating,Verbal,5,2,3,No,Highly Collaborating,1,Peer Discussion,2,Beginner
3,3,Yes,Data Analysis,Yes,Neutral,Written,5,2,1,No,Highly Collaborating,1,Study Group,2,Beginner
4,4,Yes,NLP,Yes,Enjoy Communicating,Verbal,8,2,2,No,Neutral,1,TextBook,2,Beginner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,245,No,Computer Vision,Yes,Dislike,Written,1,7,8,Yes,Neutral,7,Study Group,8,Advanced
746,246,Yes,Computer Vision,No,Neutral,Written,9,8,7,Yes,Neutral,7,Peer Discussion,7,Advanced
747,247,No,NLP,Yes,Neutral,Written,5,10,8,Yes,Neutral,10,TextBook,7,Advanced
748,248,Yes,NLP,No,Neutral,Verbal,3,7,10,Yes,Highly Collaborating,8,Peer Discussion,9,Advanced
749,249,Yes,Deep Learning,Yes,Neutral,Written,4,8,9,Yes,Neutral,8,Study Group,9,Advanced

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [9]:
x=df.iloc[:,1:12]
y=df.iloc[:,-1]
df.isna().sum()

Unnamed: 0          0
Group               0
Area                0
exploration         0
communication       0
feedback            0
extracurriculars    0
help_others         0
confidence          0
adv_courses         0
Colab               0
Exp                 0
Resouce             0
hours               0
class               0
dtype: int64